Create add.cpp
CollectorContributor/Hacktoberfest-Code-Mania pull request #3
Opened 2021-10-22 07:27 UTC by decentlearner

adding numbers in cpp.

2021-10-22 07:30 UTC, CollectorContributor commented
@decentlearner 
_

- Please Create an issue of it and mention it in this merge request, also rename the file as an Addition.CPP

_

2021-10-22 07:37 UTC, CollectorContributor requested changes
**It has compilation error,**

- on line number 8 , it should have return 0, instead of return o

2021-10-22 07:40 UTC, CollectorContributor commented
@decentlearner am closing this merge request, please remove errors from code and create an issue of and resend the merge request

2021-10-22 07:40 UTC, closed without merging

2022-10-15 06:15 UTC, vedant237 reviewed
Declared the data type of 'sum' variable

2022-10-15 06:15 UTC, vedant237 commented on add.cpp
> +  int a, b; // variable declaration of integer type.
int a, b, sum ;